# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6f9a6e5bc649ee90424e6ca703f4cf21f80e51bdefe38c3d5d53412ea69a1762a8a0aca13f60aa250a02d28c44873974d239c4200254c41989fc247bced047c

test:
  secret_key_base: 532789c1014588e0e8393a5feaf6a2ea1b009593e1e117c4075175f75d80b327418209cbd4e206a250d1d9462533e33085e5011343ede574a7862303463f094d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
